### ISSUE TITLE
[Database] Add OrderOrganization table

### ISSUE THREAD

**Issue by mrnonz** [mrnonz/mejai#55]
***Detail***
Use for store organization list in such Order.

***Tasks***
- [x] Create table Order_Organization
- [x] Update table Order
- [x] Update table Organization
